###
# Recuperer du premier commentaires
http://chara-redif.vpnuser.lan:8055/items/commentary/1

###
https://oblogback-production.up.railway.app/assets/article?field=pictures

###
# Récupération du premier article
https://directus-oblog.up.railway.app/items/commentary


###
# Récuparation d'un user 
http://chara-redif.vpnuser.lan:8055/items/article?fields=user_id

###
http://chara-redif.vpnuser.lan:8055/users/fb2f60c3-7553-4c36-8445-71f64d6d3891



###
POST http://chara-redif.vpnuser.lan:8055/items/article HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJjYTY3NTk1LWQ5ZDEtNDA0Yy05ZDgwLTIxOTVmZjJiOTNhZCIsInJvbGUiOiJlNjkwMTUyMy1kMmVkLTRiZjEtYmNmYi0wODExODcyOGM0N2UiLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY4MzExMzAzNiwiZXhwIjoxNjgzMTEzOTM2LCJpc3MiOiJkaXJlY3R1cyJ9.7ypnP-7ugSCTafA2t8OvpKuCv5QDMlTVgD2ScTzwxp8
Content-Type: application/json

{       
        
      "title": "La France et Avignon",
      "content": "Avignon, c'est beau, mais malgré son beau palais des papes, son pont d'avignon est une arnaque",
      "category_id": 1
    }


###
#se connecter en tant qu utilisateur de directus

POST  HTTP://chara-redif.vpnuser.lan:8055/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin@example.com",
    "password":"1234"
}


###
# Chargement list article trié chronologiquement et affichage limité à 3
http://chara-redif.vpnuser.lan:8055/items/article?sort=-created_at&limit=3&fields=*.*,pictures

###
http://chara-redif.vpnuser.lan:8055/items/commentary?filter[article_id][_eq]=article_id HTTP/1.1
Content-Type: application/json

{
    "email":"admin@example.com",
    "password":"1234"
}
###

http://chara-redif.vpnuser.lan:8055/items/article?fields=id
###

http://chara-redif.vpnuser.lan:8055/items/article

###
http://chara-redif.vpnuser.lan:8055/items/article?fields=id, title, pictures, author, content, category_id
###
http://chara-redif.vpnuser.lan:8055/items/article?fields=*.*.*&sort=-created_at&limit=3

###
http://chara-redif.vpnuser.lan:8055/items/commentary?filter=[article_id][_eq]=article_id


###
http://chara-redif.vpnuser.lan:8055/items/commentary?filter=[user_id][_eq]=adcca067-dc11-498c-a0f1-303ed8d1bc53

###
POST  HTTP://chara-redif.vpnuser.lan:8055/users/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJjYTY3NTk1LWQ5ZDEtNDA0Yy05ZDgwLTIxOTVmZjJiOTNhZCIsInJvbGUiOiJlNjkwMTUyMy1kMmVkLTRiZjEtYmNmYi0wODExODcyOGM0N2UiLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY4MjY4MzgxOSwiZXhwIjoxNjgyNjg0NzE5LCJpc3MiOiJkaXJlY3R1cyJ9.XVUdHxnapZNIiR2GIvspra8ce817ibOhAcu-dIwndi0
content-type: application/json

{      "id":"",
        "first_name": "Gilou",
      "last_name": "Olivier",
      "email": "oliv@msn.com",
      "password": "1234",
      "location": null,
      "title": null,
      "description": null,
      "tags": null,
      "avatar": null,
      "language": null,
      "theme": "auto",
      "tfa_secret": null,
      "status": "active",
      "role": "f3bb8d0e-b035-4c9c-8ce7-928dd1171be9",
      "token": null,
      "last_access": null,
      "last_page": null,
      "provider": "default",
      "external_identifier": null,
      "auth_data": null,
      "email_notifications": true,
      "user_name": "Giloliv",
      "commentary": [],
}


### Test comments
POST  HTTP://chara-redif.vpnuser.lan:8055/items/commentary HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJjYTY3NTk1LWQ5ZDEtNDA0Yy05ZDgwLTIxOTVmZjJiOTNhZCIsInJvbGUiOiJlNjkwMTUyMy1kMmVkLTRiZjEtYmNmYi0wODExODcyOGM0N2UiLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY4MzEyMTc2MywiZXhwIjoxNjgzMTIyNjYzLCJpc3MiOiJkaXJlY3R1cyJ9.o7I6WYUUiezx8lxkXvALCNoPaBzq9UgKpBwIOZ5Wl-I
content-type: application/json

    {
     
        "text": "marion n'en a pas vu",
        "article_id":"32",
      
        "author": "f6d187d8-d9d1-42a4-9da6-97e50ab1055b"
    }

###
http://chara-redif.vpnuser.lan:8055/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJjYTY3NTk1LWQ5ZDEtNDA0Yy05ZDgwLTIxOTVmZjJiOTNhZCIsInJvbGUiOiJlNjkwMTUyMy1kMmVkLTRiZjEtYmNmYi0wODExODcyOGM0N2UiLCJhcHBfYWNjZXNzIjoxLCJhZG1pbl9hY2Nlc3MiOjEsImlhdCI6MTY4MzExOTIzMiwiZXhwIjoxNjgzMTIwMTMyLCJpc3MiOiJkaXJlY3R1cyJ9.6Fqkddh_Hh5r6wAHdGEfW7qW2xOmKCMCfsq-RzbJs7k



###
HTTP://chara-redif.vpnuser.lan:8055/items/category

