###
# Recuperer du premier commentaires
http://chara-redif.vpnuser.lan:8055/items/commentary/1

###
# Récupération du premier article
http://chara-redif.vpnuser.lan:8055/items/article/4

###
# Récuparation d'un user 
http://chara-redif.vpnuser.lan:8055/items/user/
